### ISSUE TITLE
rollAttack and spellLevel

### ISSUE THREAD

**Issue by DarKDinDoN** [ElfFriend-DnD/foundryvtt-more-hooks-5e#8]
Hello,

Do you think it is possible to get the level at which a spell attack is cast?
Right now, the level nor the original chat card id can be retrieved. So we can't really manipulate things dependent on the spell level.

**Comment by akrigline** [comment]
ahh, in cases where the spell is upcast, the `item` provided by the rollAttack hook doesn't reflect that upcasting?

**Comment by akrigline** [comment]
Can you do me a favor and check if the 0.6.x pre-release does?
https://github.com/ElfFriend-DnD/foundryvtt-more-hooks-5e/releases/tag/0.6.1

**Comment by DarKDinDoN** [comment]
@akrigline Just tested 0.6, same behavior. Spell level isn't provided.

**Comment by akrigline** [comment]
Looking into this now.

Hooks that do show the right `data.data.level` in the Item data:
- Item5e.preRoll --> Happens before level is picked.
- Item5e.preRollConsumption
- Item5e.displayCard
- Item5e.roll

So the problem must be in the process by which a chat button for "Attack" and "Damage" provides or creates the item being rolled on the fly.

...

Looking through the 5e source. I think I see the problem.

https://github.com/foundryvtt/dnd5e/blob/master/module/item/entity.js#L1580

This is the section of code which handles rolling an attack based on chat card. Note that `spellLevel` above this is parsed directly from the chat card DOM, and not actually applied to the `item` instance that the rollAttack is invoked from.

I'm afraid fixing this is going to be beyond this module's scope, but perhaps this is worth fixing in the system.
