### ISSUE TITLE
FVTT Version 10 Build 284 Compatibility and DnD 5E v 2.0.2

### ISSUE THREAD

**Issue by CharlesHunter** [ElfFriend-DnD/foundryvtt-more-hooks-5e#9]
When I load Foundry with this mod loaded, I get the following errors:
```
GET http://192.168.0.201:23401/systems/dnd5e/module/actor/entity.js net::ERR_ABORTED 404 (Not Found)  applyDamage.js:1
GET http://192.168.0.201:23401/systems/dnd5e/module/item/entity.js net::ERR_ABORTED 404 (Not Found)  damageRoll.js:1
```

**Comment by akrigline** [comment]
This module is not marked as ready for core v10.

Nor will it ever be, the hooks introduced here were put into dnd5e v2.

**Comment by CharlesHunter** [comment]
Ah, ok.  Items with Rollable Tables required it.  Sorry for the misunderstanding. :)
